#!/bin/sh
#
# Directory Service Command Line (DCSL): query the maximum user id number.
#
# Syntax:
#
#     dscl-user-id-max
#
# Example:
#
#     $ dscl-user-id-max
#     503
#
# ## About
#
#   * Program: dscl-user-id-max
#   * Version: 1.1.0
#   * Created: 2016-02-04
#   * Updated: 2016-02-09
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
dscl . -list /Users UniqueID |
awk '{if (max=="" || $2>max){ max=$2 }} END {print max}'
